version: "3.8"
services:
  frontend:
    build: ./fineances-fe
    ports:
      - "8080:8080"
    volumes:
      - ./fineances-fe:/app
      - ./app/node_modules
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
  backend:
    build: ./fineances-be
    ports:
      - "3000:3000"
    volumes:
      - ./fineances-be:/app
      - ./app/node_modules
    depends_on:
      - db
volumes:
  mongodb:
